apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector-xray
  namespace: monitoring
spec:
  mode: deployment
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "500m"
  serviceAccount: adot-collector
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*/otel-collector/*.log
        start_at: end
        include_file_path: true
        include_file_name: true
        operators:
          - type: container
            id: container-parser
    processors:
      k8sattributes:
        auth_type: 'serviceAccount'
        extract:
          metadata:
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.pod.start_time
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.node.name
          annotations:
            - tag_name: a1
              key: annotation-one
              from: pod
            - tag_name: a2
              key: annotation-two
              regex: field=(?P<value>.+)
              from: namespace
          labels:
            - tag_name: l1
              key: label1
              from: namespace
            - tag_name: l2
              key: label2
              regex: field=(?P<value>.+)
              from: pod
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      batch/logs:
        timeout: 1s
        send_batch_size: 100
    exporters:
      awsxray:
        region: ap-northeast-2
      loki:
        endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, batch/traces]
          exporters: [awsxray]
        logs:
          receivers: [filelog]
          processors: [k8sattributes, batch/logs]
          exporters: [loki]
