apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fairytale
  name: back-fairytale
  namespace: fairytale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fairytale
  template:
    metadata:
      labels:
        app: fairytale
    spec:
      containers:
      - image: 781788730003.dkr.ecr.ap-northeast-2.amazonaws.com/eks/eks-repo/fairytale:e3
        name: fairytale
        ports:
        - containerPort: 8082


        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DB_WRITE_PASSWORD
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL

---
apiVersion: v1
kind: Service
metadata:
  name: fairytale-service
  namespace: fairytale
spec:
  selector:
    app: fairytale
  ports:
  - name: fairytale
    targetPort: 8082
    port: 8082
  type: ClusterIP
