apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: member
  name: back-member
  namespace: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      serviceAccountName: secrets-store-csi-driver 
      containers:
      - name: back-member
        image: 781788730003.dkr.ecr.ap-northeast-2.amazonaws.com/eks/eks-repo/member:e1
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "multi-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: member
spec:
  selector:
    app: member
  ports:
  - name: member
    targetPort: 8081
    port: 8081
  type: ClusterIP