apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: member
  name: back-member
  namespace: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
      - image: 781788730003.dkr.ecr.ap-northeast-2.amazonaws.com/eks/eks-repo/member:v1
        name: back-member
        ports:
        - containerPort: 8081

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

  
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DB_WRITE_PASSWORD
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL

---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: member
spec:
  selector:
    app: member
  ports:
  - name: member
    targetPort: 8081
    port: 8081
  type: ClusterIP
  
