apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-allow-ingress
  namespace: monitoring-net
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: front-net
    - podSelector:
        matchLabels: {}

  - from:
    - namespaceSelector:
        matchLabels:
          app: back-net
    - podSelector:
        matchLabels: {}
