apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-nginx-proxy
  namespace: back-net
  labels:
    app: back-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-net
  template:
    metadata:
      labels:
        app: back-net
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret 
      containers:
      - name: nginx
        image: 192.168.2.141:443/k8s-project/nginx:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: fairytale-service  # VirtualService에서 참조하는 이름
  namespace: back-net
spec:
  selector:
    app: back-net
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
