apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back-net
  name: back-deploy-seoul
  namespace: back-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-net
  template:
    metadata:
      labels:
        app: back-net
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - image: 192.168.2.141:443/k8s-project/backend-fairytale-service:v1
        name: fairytale-frankfrut
        ports:
        - containerPort: 7004
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DB_WRITE_PASSWORD
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_SERVICE_NAME
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_TRACES_SAMPLER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_TRACES_SAMPLER
        - name: OTEL_PROPAGATORS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_PROPAGATORS
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back-net
  name: back-member
  namespace: back-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-net
  template:
    metadata:
      labels:
        app: back-net
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - image: 192.168.2.141:443/k8s-project/backend-member-service:v1
        name: back-member
        ports:
        - containerPort: 8081
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DB_WRITE_PASSWORD
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_SERVICE_NAME
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_TRACES_SAMPLER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_TRACES_SAMPLER
        - name: OTEL_PROPAGATORS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_PROPAGATORS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back-net
  name: back-bookstore
  namespace: back-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-net
  template:
    metadata:
      labels:
        app: back-net
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - image: 192.168.2.141:443/k8s-project/backend-bookstore-service:v1
        name: back-bookstore
        ports:
        - containerPort: 8083
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DB_WRITE_PASSWORD
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_SERVICE_NAME
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_TRACES_SAMPLER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_TRACES_SAMPLER
        - name: OTEL_PROPAGATORS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_PROPAGATORS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back-net
  name: back-report
  namespace: back-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-net
  template:
    metadata:
      labels:
        app: back-net
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - image: 192.168.2.141:443/k8s-project/backend-report-service:v1
        name: back-report
        ports:
        - containerPort: 8083
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: DB_WRITE_PASSWORD
        - name: DB_WRITE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_USERNAME
        - name: DB_READ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_USERNAME
        - name: DB_WRITE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_WRITE_URL
        - name: DB_READ_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_READ_URL
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_SERVICE_NAME
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_EXPORTER_OTLP_PROTOCOL
        - name: OTEL_TRACES_SAMPLER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_TRACES_SAMPLER
        - name: OTEL_PROPAGATORS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: OTEL_PROPAGATORS


---
apiVersion: v1
kind: Service
metadata:
  name: fairytale-service
  namespace: back-net
spec:
  selector:
    app: back-net
  ports:
  - name: seoul
    targetPort: 7004
    port: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: back-net
spec:
  selector:
    app: back-net
  ports:
  - name: member
    targetPort: 8081
    port: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
  namespace: back-net
spec:
  selector:
    app: back-net
  ports:
  - name: member
    targetPort: 8083
    port: 8083
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: back-net
spec:
  selector:
    app: back-net
  ports:
  - name: report
    targetPort: 8084
    port: 8084
  type: ClusterIP


