apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    type: local
    app: monitoring
spec:
  storageClassName: prom
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prometheus"
  persistentVolumeReclaimPolicy: Retain
