apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moai-front
  name: moai-front
  namespace: front-net
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
    spec:
      containers:
      - image: 781788730003.dkr.ecr.ap-northeast-2.amazonaws.com/eks/eks-repo/moai-front:v40
        name: moai-front
        ports: 
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: BACKEND_URL
        - name: NEXT_PUBLIC_REDIRECT_URI
          valueFrom:
            configMapKeyRef: 
              name: frontend-config
              key: NEXT_PUBLIC_REDIRECT_URI
        - name: EXTERNAL_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: EXTERNAL_API_URL
        - name: COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: COGNITO_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: moai-front-svc
  namespace: front-net
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "application"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:ap-northeast-2:781788730003:certificate/e3ed6405-6b9b-4d8c-a03f-739b28288055"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0516390c74768a7ef,subnet-07e8033e13c0e5fce"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: front