apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moai-front
  name: moai-front
  namespace: front-net
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
      - image: 192.168.2.141:443/k8s-project/moai-front:v30
        name: moai-front
        ports: 
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: BACKEND_URL
        - name: NEXT_PUBLIC_REDIRECT_URI
          valueFrom:
            configMapKeyRef: 
              name: frontend-config
              key: NEXT_PUBLIC_REDIRECT_URI
        - name: EXTERNAL_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: EXTERNAL_API_URL
        - name: COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: front-secret
              key: COGNITO_CLIENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: moai-front-svc
  namespace: front-net
spec:
  selector:
    app: front
  ports:
  - targetPort: 3000
    port: 3000
    nodePort: 32222
  type: NodePort


