apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
  labels:
    type: local
    app: tempo
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/tempo"
  persistentVolumeReclaimPolicy: Retain
